version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: eventease-postgres-dev
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    env_file:
      - ../.env

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: eventease-backend-dev
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      NODE_ENV: development
    volumes:
      - ..:/app
      - /app/node_modules
    depends_on:
      - postgres
    command: npm run start:dev
    env_file:
      - ../.env

volumes:
  postgres_data_dev:
