version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: eventease-postgres-prod
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - backend-network
    env_file:
      - ../.env

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    container_name: eventease-backend-prod
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres
    networks:
      - backend-network
    env_file:
      - ../.env

networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data_prod:
